apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-23
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-23
    app.kubernetes.io/part-of: purple-mermaid-app
  name: java-springboot-23
  namespace: sbudhwar-1
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: java-springboot-23
status:
  loadBalancer: {}
