apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-latest-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-latest-2
    app.kubernetes.io/part-of: purple-mermaid-app
  name: demo-latest-2
  namespace: sbudhwar-1
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: demo-latest-2
status:
  loadBalancer: {}
