apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: basic-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: basic-quarkus
    app.kubernetes.io/part-of: purple-mermaid-app
  name: basic-quarkus
  namespace: sbudhwar-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: basic-quarkus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: basic-quarkus
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:sbudhwar-1-basic-quarkus
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
